### PR TITLE
Fix iptables rules

### PR DESCRIPTION
**Pull request by bogdando**
On Nemesis start, drop related, established as well

Partially closes
https://github.com/aphyr/jepsen/issues/102

Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

### CODE REVIEW

**Comment by bogdando** [comment]
sup :)

**Comment by aphyr** [comment]
Related and established connections are *already* dropped. There's no reason to do this; it just allows through untracked and invalid packets, which is *not* what Jepsen wants to do.

**Comment by bogdando** [comment]
The simple check may show that the blocking rule as-is will not affect some of connections and traffic will still flow after the nemesis start

**Comment by bogdando** [comment]
I see, for the clean env you recommend in the setup guide, w/o accepting iptables rules, this works well. But if Jepsen framework is supposed to be used with arbitrary n1..n5 nodes, there *may* be ACCEPT rules for the cluster under test pre-created. Then, the rule will not match related traffic.

**Pull request closed without merging**
